language: "Romanian"
translation_mapping:
  "personality": "personalitate"
  "the personality of God": "personalitatea lui Dumnezeu"
  "quality or state being a person": "caracteristica sau starea prin care cineva este definit ca persoană"
  "the quality or state of God being a person": "caracteristica sau starea prin care Dumnezeu este definit ca persoană"
  "the express image of His person": "Întipărirea persoanei Lui"
  "fundamental principles": "principii fundamentale"
  "foundation principles": "principii de bază"
  "fundamental beliefs": "puncte fundamentale de credință"
  "pillars of our faith": "stâlpii credinței noastre"
  "waymarks": "pietre de hotar"
  "sentiments": "opinii"
  "Ellen White": "Ellen White"
  "Seventh-day Adventist Church": "Biserica Adventistă de Ziua a Șaptea"
  "The Living Temple (the book)": "Templul viu"
  "spiritualism": "spiritualism"
  "spiritualizers": "cei care spiritualizează"
  "the spiritual view": "perspectiva spiritualistă"
  "controversy": "controversă"
  "Testimonies for the Church Containing Letters to Physicians and Ministers Instruction to Seventh-Day Adventists": "Mărturii pentru Biserică – Scrisori către medici și pastori, îndrumări pentru adventiștii de ziua a șaptea"
  "the Trinity doctrine": "doctrina Trinității"
  "patchwork theories": "teorii de peticire"
  "A Declaration of the Fundamental Principles, Taught and Practiced by the Seventh-Day Adventists": "O declarație a principiilor fundamentale, crezute și practicate de adventiștii de ziua a șaptea"
  "schorlars": "Învățați"
bible_verse_translation: "Versiunea Dumitru Cornilescu"